@AngularApp3.Server_HostAddress = http://localhost:5098




GET {{AngularApp3.Server_HostAddress}}/publicholiday/australia/2023-01-01/2023-01-20
Accept: application/json
###

GET {{AngularApp3.Server_HostAddress}}/publicholiday/phillipines/2023-01-01/2023-01-20
Accept: application/json
###

GET {{AngularApp3.Server_HostAddress}}/publicholiday/packistan/2023-01-01/2023-01-20
Accept: application/json
###
